/* Auto-generated by conf_helpers/versions.py at Sphinx-build
 * start. Lists OpenCV documentation versions >= 3.0.0, scraped
 * live from docs.opencv.org. Read by
 * _templates/opencv-version-switcher.html to populate the navbar
 * dropdown — do not edit by hand, regenerate via a fresh build. */
window.OPENCV_VERSIONS = {
  "current": "5.0",
  "versions": [
    {
      "label": "4.14.0-dev",
      "url": "https://docs.opencv.org/4.x/"
    },
    {
      "label": "4.13.0",
      "url": "https://docs.opencv.org/4.13.0/"
    },
    {
      "label": "4.12.0",
      "url": "https://docs.opencv.org/4.12.0/"
    },
    {
      "label": "4.11.0",
      "url": "https://docs.opencv.org/4.11.0/"
    },
    {
      "label": "4.10.0",
      "url": "https://docs.opencv.org/4.10.0/"
    },
    {
      "label": "4.9.0",
      "url": "https://docs.opencv.org/4.9.0/"
    },
    {
      "label": "4.8.0",
      "url": "https://docs.opencv.org/4.8.0/"
    },
    {
      "label": "4.7.0",
      "url": "https://docs.opencv.org/4.7.0/"
    },
    {
      "label": "4.6.0",
      "url": "https://docs.opencv.org/4.6.0/"
    },
    {
      "label": "4.5.5",
      "url": "https://docs.opencv.org/4.5.5/"
    },
    {
      "label": "4.5.4",
      "url": "https://docs.opencv.org/4.5.4/"
    },
    {
      "label": "4.5.3",
      "url": "https://docs.opencv.org/4.5.3/"
    },
    {
      "label": "4.5.2",
      "url": "https://docs.opencv.org/4.5.2/"
    },
    {
      "label": "4.5.1",
      "url": "https://docs.opencv.org/4.5.1/"
    },
    {
      "label": "4.5.0",
      "url": "https://docs.opencv.org/4.5.0/"
    },
    {
      "label": "4.4.0",
      "url": "https://docs.opencv.org/4.4.0/"
    },
    {
      "label": "4.3.0",
      "url": "https://docs.opencv.org/4.3.0/"
    },
    {
      "label": "4.2.0",
      "url": "https://docs.opencv.org/4.2.0/"
    },
    {
      "label": "4.1.2",
      "url": "https://docs.opencv.org/4.1.2/"
    },
    {
      "label": "4.1.1",
      "url": "https://docs.opencv.org/4.1.1/"
    },
    {
      "label": "4.1.0",
      "url": "https://docs.opencv.org/4.1.0/"
    },
    {
      "label": "4.0.1",
      "url": "https://docs.opencv.org/4.0.1/"
    },
    {
      "label": "4.0.0",
      "url": "https://docs.opencv.org/4.0.0/"
    },
    {
      "label": "3.4.20-dev",
      "url": "https://docs.opencv.org/3.4/"
    },
    {
      "label": "3.4.20",
      "url": "https://docs.opencv.org/3.4.20/"
    },
    {
      "label": "3.4.19",
      "url": "https://docs.opencv.org/3.4.19/"
    },
    {
      "label": "3.4.18",
      "url": "https://docs.opencv.org/3.4.18/"
    },
    {
      "label": "3.4.17",
      "url": "https://docs.opencv.org/3.4.17/"
    },
    {
      "label": "3.4.16",
      "url": "https://docs.opencv.org/3.4.16/"
    },
    {
      "label": "3.4.15",
      "url": "https://docs.opencv.org/3.4.15/"
    },
    {
      "label": "3.4.14",
      "url": "https://docs.opencv.org/3.4.14/"
    },
    {
      "label": "3.4.13",
      "url": "https://docs.opencv.org/3.4.13/"
    },
    {
      "label": "3.4.12",
      "url": "https://docs.opencv.org/3.4.12/"
    },
    {
      "label": "3.4.11",
      "url": "https://docs.opencv.org/3.4.11/"
    },
    {
      "label": "3.4.10",
      "url": "https://docs.opencv.org/3.4.10/"
    },
    {
      "label": "3.4.9",
      "url": "https://docs.opencv.org/3.4.9/"
    },
    {
      "label": "3.4.8",
      "url": "https://docs.opencv.org/3.4.8/"
    },
    {
      "label": "3.4.7",
      "url": "https://docs.opencv.org/3.4.7/"
    },
    {
      "label": "3.4.6",
      "url": "https://docs.opencv.org/3.4.6/"
    },
    {
      "label": "3.4.5",
      "url": "https://docs.opencv.org/3.4.5/"
    },
    {
      "label": "3.4.4",
      "url": "https://docs.opencv.org/3.4.4/"
    },
    {
      "label": "3.4.3",
      "url": "https://docs.opencv.org/3.4.3/"
    },
    {
      "label": "3.4.2",
      "url": "https://docs.opencv.org/3.4.2/"
    },
    {
      "label": "3.4.1",
      "url": "https://docs.opencv.org/3.4.1/"
    },
    {
      "label": "3.4.0",
      "url": "https://docs.opencv.org/3.4.0/"
    },
    {
      "label": "3.3.1",
      "url": "https://docs.opencv.org/3.3.1/"
    },
    {
      "label": "3.3.0",
      "url": "https://docs.opencv.org/3.3.0/"
    },
    {
      "label": "3.2.0",
      "url": "https://docs.opencv.org/3.2.0/"
    },
    {
      "label": "3.1.0",
      "url": "https://docs.opencv.org/3.1.0/"
    },
    {
      "label": "3.0.0",
      "url": "https://docs.opencv.org/3.0.0/"
    }
  ]
};
